### PR TITLE
add RSA+ECDSA pins for rgnet-iad.anycast.censurfridns.dk node v4+v6

### PR DESCRIPTION
**Pull request by tykling**
Hello :)

Just a small update to add RSA + ECDSA pins for a recently revived anycast node in Washington, USA: `rgnet-iad.anycast.censurfridns.dk`

Best regards and a happy new year

/Thomas

### CODE REVIEW

**Comment by tykling** [comment]
These pins have been published in the DNS as TLSA records as well, in case verification is needed :)

**Comment by ntninja** [comment]
```
      - digest: "sha256"
        value: 97tijP/z/JpGmYN3fuWTuTYl6zYripxVOEv2V2iBa8Y=
      - digest: "sha256"
        value: 9FmNCbxBrYzAlges3DXuWICjvUSMY/vxlNSeqDleLTw=
      - digest: "sha256"
        value: Y4gU6vmrYSpNykdq0S1Po7Ar9sBFj26KAOKIcJQyoX8=
      - digest: "sha256"
        value: x72/vIQoOu7mCuu1cSbeqOZNv9u+mK/2UtKjXDi0hto=
```

@tykling: Are these the shut down Solido and Bornfibre nodes? Should they be removed or kept in the config?

**Comment by tykling** [comment]
hm, I think so, but I would have to check. This would be a lot easier if there was a comment line for each key (so digest, value, comment for each)

I will make a new PR removing the keys for the retired nodes, thanks for reminding me :)

**Comment by saradickinson** [comment]
@tykling thanks for trying to keep your keys up to date (and apologies for a long time since last release) - we are hoping to do start a release this week so if you need to remove some keys please do asap :-)

**Pull request merged**
